//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub refresh_token: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sms::Entity")]
    Sms,
}

impl Related<super::sms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
